#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : llvmlite
Version  : 0.29.0
Release  : 28
URL      : https://github.com/numba/llvmlite/archive/v0.29.0/llvmlite-0.29.0.tar.gz
Source0  : https://github.com/numba/llvmlite/archive/v0.29.0/llvmlite-0.29.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: llvmlite-license = %{version}-%{release}
Requires: llvmlite-python = %{version}-%{release}
Requires: llvmlite-python3 = %{version}-%{release}
Requires: enum34
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : enum34
BuildRequires : llvm
BuildRequires : llvm-dev

%description
========
llvmlite
========
.. image:: https://travis-ci.org/numba/llvmlite.svg?branch=master
:target: https://travis-ci.org/numba/llvmlite
:alt: Travis CI
.. image:: https://codeclimate.com/github/numba/llvmlite/badges/gpa.svg
:target: https://codeclimate.com/github/numba/llvmlite
:alt: Code Climate
.. image:: https://coveralls.io/repos/github/numba/llvmlite/badge.svg
:target: https://coveralls.io/github/numba/llvmlite
:alt: Coveralls.io
.. image:: https://readthedocs.org/projects/llvmlite/badge/
:target: https://llvmlite.readthedocs.io
:alt: Readthedocs.io

%package license
Summary: license components for the llvmlite package.
Group: Default

%description license
license components for the llvmlite package.


%package python
Summary: python components for the llvmlite package.
Group: Default
Requires: llvmlite-python3 = %{version}-%{release}

%description python
python components for the llvmlite package.


%package python3
Summary: python3 components for the llvmlite package.
Group: Default
Requires: python3-core

%description python3
python3 components for the llvmlite package.


%prep
%setup -q -n llvmlite-0.29.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559658744
export CC=clang
export CXX=clang++
export LD=ld.gold
unset LDFLAGS
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/llvmlite
cp LICENSE %{buildroot}/usr/share/package-licenses/llvmlite/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/llvmlite/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
